title: Tamilarasu Ganeshamurthy
description: "Researcher in High-Pressure Luminescence | Nanophosphors & WLEDs"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"

# Author Profile (Sidebar)
author:
  name: "Tamilarasu Ganeshamurthy"
  bio: "Specializing in RE-doped nanophosphors and high-pressure synthesis."
  location: "Tamil Nadu, India"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:tamilarasu9486@gmail.com"

# Plugin Settings
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Site Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
